blog/config/routes.rb
Rails.application.routes.draw do
  get 'articles/new'
  get 'articles/index'
  get 'articles/show'
  get 'articles/edit'
  get 'articles/update'
  get 'articles/destroy'
  get 'articles/_form'
  post '/articles/index'
  post '/articles/new'
  post '/articles/show'
  post '/articles/edit'
  post '/articles/update'
  post '/articles/destroy'
  post '/articles/_form'

     resources :articles

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true,
                    length: { minimum: 5 }
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
 def index
  @articles = Article.all
end
def new
   @article = Article.new
  end
  def create
   @article = Article.new(article_params)
  if @article.save
    redirect_to @article
  else
    render 'new'
  end
end
  def show
  @article = Article.find(params[:id])
end
def edit
  @article = Article.find(params[:id])
end
def update
  @article = Article.find(params[:id])
  
  if @article.update(article_params)
    redirect_to @article
  else
    render 'edit'
  end
end
  def destroy
  @article = Article.find(params[:id])
  @article.destroy
 
  redirect_to articles_path
end
private
  def article_params
    params.require(:article).permit(:title, :text)
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@article.errors.count, "error") %> prohibited
      this article from being saved:</h2>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

blog/app/views/articles/edit.html.erb
<h1>Editing article</h1>
 
<%= form_for :article, url: article_path(@article), method: :patch do |f| %>
 <%= render 'form' %>
<%= link_to 'Back', articles_path %>
<% end %>

blog/app/views/articles/index.html.erb
<h1>Listing articles</h1>
 <%= link_to 'New article', new_article_path %>
<table border='1'>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    <td><%= link_to 'Edit', edit_article_path(article) %></td>
    <td><%= link_to 'Destroy', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>Articles#new</h1>
<%= form_for :article, url: articles_path do |f| %>
<%= render 'form' %>
<%= link_to 'Back', articles_path %>
<% end %>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', articles_path %>
| <%= link_to 'Edit', edit_article_path(@article) %>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>